const FRConstants = {
    Hiring: "EMBAUCHE",
    Artisan: "ARTISAN",
    Support: "SUPPORT",
    carousel: "Trouvez vos artisans préférés, comparez les prix et faites le travail à temps !",
    startHiring: "COMMENCEZ À EMBAUCHE",
    artisansNumber: '7000 Artisans',
    jobOffersNumber: '2000 Offres Envoyées',
    estimationsSentNumber: '10000 Estimations',
    hiresNumbers: '1000 travail effectué',
    PrivacyPolicy: 'POLITIQUE DE CONFIDENTIALITÉ',
    AboutUs:"À PROPOS D'ARTISAN",
    TermsOfService: "CONDITIONS D'UTILISATION",
    GooglePlay: 'GOOGLE PLAY',
    AppleStore: 'APP STORE',
    clientsNumber: '5000 CLIENTS',
    hireRate: "75% DE TAUX D'EMBAUCHE",
    city: "Ville",
    carouselArtisan: "Devenez l'un de nos partenaires de confiance pour être embauché facilement et gagner plus",
}
export default FRConstants;